os:
  - linux

language: php

php:
  - "7.2"

services:
  - postgresql

before_install:
  - cd source/
  - cp .env.example .env
  - travis_retry composer self-update
  - composer install
  - psql -c 'create database agrotur;' -U postgres

script:
  - phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
  - bin/behat

branch:
  - master
