os:
  - linux

language: php

php:
  - "7.2"

services:
  - postgresql

before_install:
  - cd source/
  - travis_retry composer self-update
  - composer install
  - php artisan migrate:fresh

script:
  - phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests

branch:
  - master
